In [ ]:
import numpy as np

ADDITION,SUBTRACTION,MULTIPLICATION,DIVISION,MODULAR DIVISIONAND FLOOR DIVISION


In [ ]:
#ADDITION OF ARRAY
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("Given x:",x)
print("Given y:",y)
c=x+y
print("After Addition :",c)

Given x: [1 2 3 4 5]
Given y: [5 6 7 8 9]
After Addition : [ 6  8 10 12 14]


In [ ]:
#SUBTRACTION OF ARRAY
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("Given x:",x)
print("Given y:",y)
c=x-y
print("After Subtraction :",c)

Given x: [1 2 3 4 5]
Given y: [5 6 7 8 9]
After Subtraction : [-4 -4 -4 -4 -4]


In [ ]:
#MULTIPLICATION OF ARRAY
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("Given x:",x)
print("Given y:",y)
c=x*y
print("After Subtraction :",c)

Given x: [1 2 3 4 5]
Given y: [5 6 7 8 9]
After Subtraction : [ 5 12 21 32 45]


In [ ]:
#DIVISION OF ARRAY
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("Given x:",x)
print("Given y:",y)
c=x/y
print("After Division :",c)

Given x: [1 2 3 4 5]
Given y: [5 6 7 8 9]
After Division : [0.2        0.33333333 0.42857143 0.5        0.55555556]


In [ ]:
#MODULAR DIVISION OF ARRAY
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("Given x:",x)
print("Given y:",y)
c=x%y
print("After Division :",c)

Given x: [1 2 3 4 5]
Given y: [5 6 7 8 9]
After Division : [1 2 3 4 5]


In [ ]:
#FLOOR DIVISION OF ARRAY
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9,])
print("Given x:",x)
print("Given y:",y)
c=x//y
print("After Division :",c)

Given x: [1 2 3 4 5]
Given y: [5 6 7 8 9]
After Division : [0 0 0 0 0]


SUM FUNCTION


In [ ]:
a=np.array([1,2,3,4,5,6,7])
print("sum of the array is :",sum(a))

sum of the array is : 28


MAX FUNCTION

In [ ]:
a=np.array([1,2,3,4,5,6,7,'ABC'])
print("The maximum element in the array is :",max(a))

The maximum element in the array is : ABC


MIN FUNCTION


In [ ]:
a=np.array([1,2,3,4,5,6,7,'ABC'])
print("The minimum element in the array is :",min(a))

The minimum element in the array is : 1


LENGTH FUNCTION

In [ ]:
a=np.array([1,2,3,4,5,6,7])
print("The Length of the array is :",len(a))

The Length of the array is : 7


ACCESSING THE ARRAY DATA IN NUMPY IS SAME AS THE LIST DATA

In [ ]:
a=np.array([1,2,3,4,5,6,7,'abc'])
print("Given Array :",a)
print("Accessing Array :",*a)

Given Array : ['1' '2' '3' '4' '5' '6' '7' 'abc']
Accessing Array : 1 2 3 4 5 6 7 abc


USING INDEX

In [ ]:
a=np.array([1,2,3,4,5,'abc'])
for i in a:
  print(i)
for i in range(len(a)):
  print(a[i])

1
2
3
4
5
abc
1
2
3
4
5
abc


SLICING

In [ ]:
a=np.array([1,2,3,4,5,'abc'])
print("Given Array :",a)
print("After slicing",a[::-1])

Given Array : ['1' '2' '3' '4' '5' 'abc']
After slicing ['abc' '5' '4' '3' '2' '1']


ZERO'S FUNCTION

In [ ]:
# zeros()-function
# syntax:
# zeros(size,datatype)
# datatype is optional
# default is real
a=np.zeros(5,int)
print(a)


[0 0 0 0 0]


ONE'S FUNCTION

In [ ]:
a=np.ones(5,int)
print(a)

[1 1 1 1 1]


DATA TYPE

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("Data type of Given Array a:",a.dtype)
print("Data type of Given Array b:",b.dtype)

Data type of Given Array a: int64
Data type of Given Array b: int64


ARRAY DIMENSION

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("Dimension of Given Array s:",a.ndim)
print("Dimension of Given Array b:",b.ndim)

Dimension of Given Array s: 1
Dimension of Given Array b: 2


ARRAY SIZE

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("Size of Given Array a:",a.size)
print("Size of Given Array b:",b.size)

Size of Given Array a: 5
Size of Given Array b: 10


ONE DIMENSION ARRAY

In [ ]:
n=int(input("Enter the number of variables :")) #size of array
x=np.ndarray(shape=(n),dtype=int)
for i in range(n):
  v=int(input("Enter the number :"))
  x[i]=v
print("One dimension array:",x)

Enter the number of variables :3
Enter the number :2
Enter the number :3
Enter the number :5
One dimension array: [2 3 5]


Take an arary with values 10,20,15,25,30 print the indexes of evn values and odd values in the list

In [ ]:
a=np.array([10,20,15,25,30])
for i in range(len(a)):
  if(a[i]%2!=0):
     print("The indexes of the odd values are :",i)
  else:
    print("The indexes of the Even values are :",i)


The indexes of the Even values are : 0
The indexes of the Even values are : 1
The indexes of the odd values are : 2
The indexes of the odd values are : 3
The indexes of the Even values are : 4


Method-2:

In [ ]:
a=np.array([10,20,15,25,30])
ans=np.where(a%2==0) #
print("The indexes of the even values are:",*ans)
ans=np.where(a%2!=0)
print("The indexes of the odd values are:",*ans)

The indexes of the even values are: [0 1 4]
The indexes of the odd values are: [2 3]


program to print the indexes of the given particular value in the  list ex:[5,10,5,10,5,10]

In [ ]:
a=np.array([5,10,5,10,5,10])
k=int(input("Enter the value of k:"))
ans=np.where(a==k)
print(f"The indexes of the value of {k} are:",*ans)

Enter the value of k:5
The indexes of the value of 5 are: [0 2 4]


In [ ]:
n=int(input("Enter the number of variables :")) #size of array
x=np.ndarray(shape=(n),dtype=int)
for i in range(n):
  v=int(input("Enter the number :"))
  x[i]=v
k=int(input("Enter the value of k:"))
ans=np.where(a>k)
print(f"The indexes of the value of {k} which is lesser:",*ans)

Enter the number of variables :3
Enter the number :10
Enter the number :25
Enter the number :10
Enter the value of k:10
The indexes of the value of 10 which is lesser: []


Program to find the index to insert new info into the list in the correct position by maintaing the order

In [ ]:
n=int(input("Enter the number of variables :")) #size of array
x=np.ndarray(shape=(n),dtype=int)
for i in range(n):
  a=int(input("Enter the number :"))
  x[i]=a
print("Given Array :",x)
d=int(input("Enter the number to be search :"))
ans=np.searchsorted(x,d)
print(f"The number {d} is in the Index Position :{ans} ")

Enter the number of variables :3
Enter the number :21
Enter the number :32
Enter the number :365
Given Array : [ 21  32 365]
Enter the number to be search :32
The number 32 is in the Index Position :1 


SORTING

In [ ]:
n=int(input("Enter the number of variables :")) #size of array
x=np.ndarray(shape=(n),dtype=int)
for i in range(n):
  a=int(input("Enter the number :"))
  x[i]=a
print("Given Array :",x)
x.sort()
print("Sorted Array :",x)

Enter the number of variables :3
Enter the number :2
Enter the number :3
Enter the number :5
Given Array : [2 3 5]
Sorted Array : [2 3 5]


2 DIMENSIONAL ARRAY


In [ ]:
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
print("2D Array :",a)
print("Data type of Given Array a:",a.dtype) #datatype
print("Size of Given Array a:",a.size) #size
print("Dimension of Given Array s:",a.ndim) #dimension of array
print("Shape of Given Array a:",a.shape) #shape of array


2D Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type of Given Array a: int64
Size of Given Array a: 9
Dimension of Given Array s: 2
Shape of Given Array a: (3, 3)


2D ARRAY INDEXING

In [ ]:
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
for i in range(3):
  for j in range(3):
    print("Index Values of given array :",a[i][j],(i,j),end=" ")
  print()

Index Values of given array : 1 (0, 0) Index Values of given array : 2 (0, 1) Index Values of given array : 3 (0, 2) 
Index Values of given array : 4 (1, 0) Index Values of given array : 5 (1, 1) Index Values of given array : 6 (1, 2) 
Index Values of given array : 7 (2, 0) Index Values of given array : 8 (2, 1) Index Values of given array : 9 (2, 2) 


 2D ARRAY MATRIX

In [ ]:
import numpy as np
x=[[1,2,3],[4,5,6],[7,8,9]]
m=np.matrix(x)
print("Matrix :",m)
print("Data type of Given Array m:",m.dtype) #datatype
print("Size of Given Array m:",m.size) #size
print("Dimension of Given Array m:",m.ndim) #dimension of array
print("Shape of Given Array m:",m.shape) #shape of array

Matrix : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type of Given Array m: int64
Size of Given Array m: 9
Dimension of Given Array m: 2
Shape of Given Array m: (3, 3)


In [ ]:
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
print(m)
print("Data type of Given Array m:",m.dtype) #datatype
ans=a.flatten()       #flatten helps to convert the multidimensional array to single dimensional array
print(ans)
ans1=m.flatten()
print(ans1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type of Given Array m: int64
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


In [ ]:
import numpy as np
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a1=a.reshape(3,3)
m1=m.reshape(3,3)
print(a1)
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


CONSTANT ADDITION ,SUBTRACTION, MULTIPLICATION, DIVISION, MODULAR DIVISION, FLOOR DIVISION

In [ ]:
#Constant Addition
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a+=2
print(a)
m+=2
print(m)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#Constant Addition
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a+=2
print(a)
m+=2
print(m)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#Constant Subtraction
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a-=2
print(a)
m-=2
print(m)

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [ ]:
#Constant ultliplication
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a*=2
print(a)
m*=2
print(m)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
#Constant Division
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a=a/2
print(a)
m=m/2
print(m)

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [ ]:
#Constant Modular Division
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a=a%2
print(a)
m=m%2
print(m)

[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [ ]:
#Constant Floor Division
x=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(x)
m=np.matrix(x)
a=a//2
print(a)
m=m//2
print(m)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[0 1 1]
 [2 2 3]
 [3 4 4]]


SUM FUNCTIO,MAX FUNCTION,MIN FUNCTION

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m=np.matrix('1 2 3; 4 5 6; 7 8 9')
print("sum of the array a is :",np.sum(a))    #for rowwise sum(axis=1)and coloumnwise sum(axis=0)
print("sum of the matrix m is :",np.sum(m))
print("The maximum element in the array a is :",np.max(a))
print("The maximum element in the matrix m is :",np.max(m))
print("The minimum element in the array a is :",np.min(a))
print("The minimum element in the matrix m is :",np.min(m))
print("The Length of the array a is :",np.size(a))
print("The Length of the matrix m is :",np.size(m))

sum of the array a is : 45
sum of the matrix m is : 45
The maximum element in the array a is : 9
The maximum element in the matrix m is : 9
The minimum element in the array a is : 1
The minimum element in the matrix m is : 1
The Length of the array a is : 9
The Length of the matrix m is : 9


PRODUCT FUNCTION


In [ ]:
#Product
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m=np.matrix('1 2 3; 4 5 6; 7 8 9')
print("Product of the array a is :",np.prod(a))
print("Product of the matrix m is :",np.prod(m))
print( "Product of the row in array a is :",a.prod(axis=1))
print( "Product of the coloumn in array a is :",a.prod(axis=0))
print( "Product of the row in matrix m is :",m.prod(axis=1))
print( "Product of the coloumn in matrix m is :",m.prod(axis=0))

Product of the array a is : 362880
Product of the matrix m is : 362880
Product of the row in array a is : [  6 120 504]
Product of the coloumn in array a is : [ 28  80 162]
Product of the row in matrix m is : [[  6]
 [120]
 [504]]
Product of the coloumn in matrix m is : [[ 28  80 162]]


TRANSPOSE


In [ ]:
# Tanspose data - Interchange of rows and columns
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m=np.matrix('1 2 3; 4 5 6; 7 8 9')
print("Transpose of the array a is :",np.transpose(a))
print("Transpose of the matrix m is :",np.transpose(m))


Transpose of the array a is : [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of the matrix m is : [[1 4 7]
 [2 5 8]
 [3 6 9]]


TRACE

In [ ]:
# Trace- performs addition of diagnol elements
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m=np.matrix('1 2 3; 4 5 6; 7 8 9')
print("The sum of diagnol elements in the array a is:",np.trace(a))
print("The sum of diagnol elements in the matrix m is:",np.trace(m))

UNIQUE

In [ ]:
#Unique
a=np.array([[1,2,2],[4,4,6],[7,7,7]])
m=np.matrix('1 2 2; 4 5 5; 7 7 7')
print("The unique elements pressent in the array a is :",np.unique(a))
print("The unique elements pressent in the matrix m is :",np.unique(m))

The unique elements pressent in the array a is : [1 2 4 6 7]
The unique elements pressent in the matrix m is : [[1 2 2 4 5 5 7 7 7]]


Write a program to find the determinant of the given matrix('6 1 1;4 -2 5;2 8 7')

In [ ]:
'''
np.linalg.det()
np=package
linalg=module
det=function '''
a=np.matrix('6 1 1;4 -2 5;2 8 7')
print("The determinant of the given matrix is :",np.linalg.det(a))

The determinant of the given matrix is : -306.0


MEAN

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m=np.matrix('1 2 3; 4 5 6; 7 8 9')
print("The mean of the array a is :",np.mean(a))
print("The mean of the matrix m is :",np.mean(m))

The mean of the array a is : 5.0
The mean of the matrix m is : 5.0


In [ ]:
import numpy as np
a=np.array([[2,4,8],[3,6,9],[1,3,2]])
m=np.matrix('2,4,8;3,6,9;1,3,2')
x=np.sort(a,axis=None)[::-1]
y=np.sort(m,axis=None)[::-1]
print(x)
print(y)

[9 8 6 4 3 3 2 2 1]
[[1 2 2 3 3 4 6 8 9]]


In [ ]:
a=np.array([[2,4,8],[3,6,9],[1,3,2]])
m=np.matrix('2,4,8;3,6,9;1,3,2')
x=(np.sort(-a,axis=0))*-1
print("",x)
y=(np.sort(-a,axis=0))*-1
print(y)

Sorted colomn array  [[3 6 9]
 [2 4 8]
 [1 3 2]]
[[3 6 9]
 [2 4 8]
 [1 3 2]]


MATRIX ADDITION OPERATION,SUBTRACTION, MULTIOLICATION OPERATION

In [ ]:
a=np.matrix('1 2 3 ;4 5 6')
b=np.matrix('1 2 3;4 5 6')
sum=a+b
print("The sum of the given Matrix is :",sum)

The sum of the given Matrix is : [[ 2  4  6]
 [ 8 10 12]]


TWO DIMENSIONAL ARRAY READ OPERATION

In [ ]:
r,c=map(int,input().split())
m=np.ndarray(shape=(r,c),dtype=int)
for i in range(r):
  for j in range(c):
    d=int(input())
    m[i][j]=d
for i in range(r):
  for j in range(c):
    print(m[i][j],(i,j),end=' ')
  print()

5


ValueError: not enough values to unpack (expected 2, got 1)

STRINGS-Set of characters grouped together.


1.Unicode strings

In [ ]:
print("vignan")#8 bit

vignan


2.Raw strings-r helps to print the data same

In [ ]:
print(r'\tvignan')

\tvignan


String Modules:

In [ ]:
import string

In [ ]:
print(string.__all__)

['ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'capwords', 'digits', 'hexdigits', 'octdigits', 'printable', 'punctuation', 'whitespace', 'Formatter', 'Template']


In [ ]:
print(string.ascii_letters)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ


In [ ]:
print(string.ascii_uppercase)

ABCDEFGHIJKLMNOPQRSTUVWXYZ


In [ ]:
print(string.ascii_lowercase)

abcdefghijklmnopqrstuvwxyz


In [ ]:
print(string.digits)

0123456789


In [ ]:
print(string.octdigits)

01234567


In [ ]:
print(string.hexdigits)

0123456789abcdefABCDEF


In [ ]:
print(string.printable)

0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ 	



In [ ]:
print(len(string.printable))

100


In [ ]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [ ]:
print(len(string.punctuation))

32


In [ ]:
print(string.whitespace)

In [ ]:
print(len(string.whitespace))

6


String boolean methods: 1.isalpha() 2.isalnum() 3.isdigit() 4.isdecimal()
5.isnumeric() 6.isspace() 7.istitle() 8.isupper() 9.islower() 10.isprintable() 11.isascii() 12.isidentifier()

In [ ]:
s1='a1'
s2='1a'  #String identifier shouldn't start with numeric value
print(s1.isidentifier())
print(s2.isidentifier())

True
False


find()-it returns the first appearance of data(str2) starting index if present in the main string(str1) else it returns -1

In [ ]:
s1="Vignan of Anil of guntur of Python"
s2="of"
print(s1.find(s2)) #from left side
print(s1.rfind(s2)) #fromright side

7
25


Center method

In [ ]:
s1="Vignan of Anil of guntur of Python"
print(s1.center(49,'@'))

@@@@@@@@Vignan of Anil of guntur of Python@@@@@@@


In [ ]:
s1="Vignan of Anil of guntur of Python"
print(s1.ljust(49,'@'))
print(s1.rjust(49,'@'))

Vignan of Anil of guntur of Python@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@Vignan of Anil of guntur of Python


In [ ]:
list1=['boo','batch','of','2025']
str='@#'
print(str.join(list1))

boo@#batch@#of@#2025


Zfill()-same as rjust()

In [ ]:
s1="Vignan of Anil of guntur of Python"
print(s1.zfill(50))

0000000000000000Vignan of Anil of guntur of Python


Program to count the uppercase alphabets,lowercase alphabets,digits and symbols present in the input string.

In [ ]:
def count_characters(s):
    upper = lower = digit = symbol = 0

    for char in s:
        if char.isupper():
            upper += 1
        elif char.islower():
            lower += 1
        elif char.isdigit():
            digit += 1
        else:
            symbol += 1

    print("Uppercase letters:", upper)
    print("Lowercase letters:", lower)
    print("Digits:", digit)
    print("Symbols:", symbol)

# Input from user
input_string = input("Enter a string: ")
count_characters(input_string)

Enter a string: vignan
Uppercase letters: 0
Lowercase letters: 6
Digits: 0
Symbols: 0
